# Questions on NumPy Array

In [2]:
import numpy as np

In [30]:
# Q.1 How to create an empty and a full numpy array.
# The empty() function in NumPy is used to create an empty array with a specified shape. An empty NumPy array is an array that 
# is initialized with arbitrary values, and its shape is determined by the user.
# The full() function in NumPy creates an array of a given shape and fills it with a specified value. A full NumPy array is an 
# array where all the elements have the same predefined value.

empty_array = np.empty((3, 4))
print("Empty array : \n",empty_array)

full_array= np.full((2, 4), 8)
print(" \n Full array : \n" ,full_array)

Empty array : 
 [[7.57926063e-312 7.57929422e-312 7.57929422e-312 7.57929406e-312]
 [7.57929406e-312 7.57929405e-312 7.57929406e-312 7.57929406e-312]
 [7.57929406e-312 7.57929406e-312 7.57929406e-312 7.57929406e-312]]
 
 Full array : 
 [[8 8 8 8]
 [8 8 8 8]]


In [33]:
# Q.2 Create a Numpy array filled with all zeros.
# To create an numpy array fielled with all zeros,we can use the numpy.zeros() function.

a = np.zeros([3,3])  
print("Array a : \n", a)  
  
b = np.zeros([3, 3], dtype = int)  
print("\n Array b : \n", b)  

Array a : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Array b : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [2]:
# Q.3 Create a numpy array filled with all ones.
# To create an array filled with all ones,given shape and type of array we can use numpy.ones() method of NumPy library in Python.

a = np.ones([3,3])  
print("Array a : \n", a)  
  
b = np.ones([3, 3], dtype = int)  
print("\n Array b : \n", b)  

Array a : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 Array b : 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
# Q.4 Check weather a numpy array contains a specified row.
# This can be done by using simple approach as checking for each row with the given list but this can be easily understood and 
# implemented by using inbuilt library functions numpy.array.tolist().If the given list is present in a array as a row then 
# the output is True else False.

arr = np.array([[6,7,8,9,10], 
                [16, 17, 20, 19, 180], 
                [1, 2, 3, 4, 5], 
                [11, 12, 13, 14, 15]]) 
 
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist()) 
print([3, 2, 5, -4, 5] in arr.tolist()) 
print([11, 12, 13, 14, 15] in arr.tolist()) 

True
False
False
True


In [12]:
# Q.5 How to Remove rows in Numpy array that contains non-numeric values?
# It is possible to remove all rows containing Nan values using the Bitwise NOT operator and np.isnan() function.

n_arr = np.array([[10, 22, 3],
                  [15,98,65],
                  [41, np.nan, np.nan]]) 
  
print("Given array:") 
print(n_arr) 
  
print("\nRemove all rows containing non-numeric elements") 
print(n_arr[~np.isnan(n_arr).any(axis=1)]) 

Given array:
[[10. 22.  3.]
 [15. 98. 65.]
 [41. nan nan]]

Remove all rows containing non-numeric elements
[[10. 22.  3.]
 [15. 98. 65.]]


In [2]:
# Q.6 Remove single-dimensional entries from the shape of an array.
# numpy.squeeze() function is used when we want to remove single-dimensional entries from the shape of an array.

input_arr = np.array([[[2, 2, 2], [2, 2, 2]]]) 
   
print ("Input array : ", input_arr)  
print("Shape of input array : ", input_arr.shape)   
  
output_arr = np.squeeze(input_arr)  
  
print ("output squeezed array : ", output_arr) 
print("Shape of output array : ", output_arr.shape)

Input array :  [[[2 2 2]
  [2 2 2]]]
Shape of input array :  (1, 2, 3)
output squeezed array :  [[2 2 2]
 [2 2 2]]
Shape of output array :  (2, 3)


In [14]:
# Q.7 Find the number of occurrences of a sequence in a NumPy array Improve
# The sequence is consisting of some elements in the form of a list and we have to find the number of occurrences of that 
# sequence in a given NumPy array. This can be done easily by checking the sequence for every iteration of ndarray. But this 
# leads to higher time so we use the concept of NumPy methods.

arr = np.array([[2, 8, 9, 4],  
                   [9, 4, 9, 4], 
                   [4, 5, 9, 7], 
                   [2, 9, 4, 3]]) 
output = repr(arr).count("9, 4") 
print(output) 

4


In [5]:
# Q.8 Find the most frequent value in a NumPy array
# step-1 Create a NumPy array.
# step-2 Apply bincount() method of NumPy to get the count of occurrences of each element in the array.
# step-3 The n, apply argmax() method to get the value having a maximum number of occurrences(frequency).

a = np.array([22,22,33,44,5,11,22,22,11,11]) 
print("Original array:") 
print(a) 
  
print("Most frequent value in the above array:") 
print(np.bincount(a).argmax())

Original array:
[22 22 33 44  5 11 22 22 11 11]
Most frequent value in the above array:
22


In [3]:
# Q.9 Combining a one and a two-dimensional NumPy Array
# Numpy has a function named as numpy.nditer(), which provides this facility.

num_1d = np.arange(5) 
print("One dimensional array:") 
print(num_1d) 
  
num_2d = np.arange(10).reshape(2,5) 
print("\nTwo dimensional array:") 
print(num_2d) 
  
for a, b in np.nditer([num_1d, num_2d]): 
    print("%d:%d" % (a, b),)

One dimensional array:
[0 1 2 3 4]

Two dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


In [4]:
# Q.10 How to build an array of all combinations of two NumPy arrays?
# Numpy has a function to compute the combination of 2 or more Numpy arrays named as “numpy.meshgrid()“. This function is used 
# to create a rectangular grid out of two given one-dimensional arrays representing the Cartesian indexing or Matrix indexing.

array_1 = np.array([1, 2]) 
array_2 = np.array([4, 6]) 
  
print("Array-1") 
print(array_1) 
  
print("\nArray-2") 
print(array_2) 
  
comb_array = np.array(np.meshgrid(array_1, array_2)).T.reshape(-1, 2) 
  
print("\nCombine array:") 
print(comb_array) 

Array-1
[1 2]

Array-2
[4 6]

Combine array:
[[1 4]
 [1 6]
 [2 4]
 [2 6]]


# function 1 np.arange()

In [10]:
# Example 1 
# Explanation : This will create an array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]. The arange() function generates values starting from 0 up to (but not including) the specified stop value, with a default step of 1.
import numpy as np 

arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Example 2 
# This will create an array [3,6,9,12,15,18,21,24,27]. The arange() function allows specifying the start, stop, and step values. In this example, it generates values starting from 3 up to (but not including) 30, with a step of 3.

arr=np.arange(3,30,3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [11]:
# Example 3 
# Explanation :This will produce an array [0. ,0.25 ,0.5 ,0.75 ], ensuring precise control over the number of elements and avoiding potential floating-point arithmetic errors.

arr = np.arange(0,1,0.25)
arr

array([0.  , 0.25, 0.5 , 0.75])

# function 2 np.sum()

In [27]:
# Example 1
# Explanation : This will sum arr1 and arr2 all elements.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Array 1 :",arr1,"\nArray 1 Sum :" ,arr1.sum() )
print("\nArray 2 :",arr2,"\nArray 2 Sum :" ,arr2.sum() )

Array 1 : [1 2 3] 
Array 1 Sum : 6

Array 2 : [4 5 6] 
Array 2 Sum : 15


In [36]:
# Example 2
# Explanation : This will first multipled arr1 and arr2 then sum of arr1 and arr2 multiplication .

arr1 = np.array([3,4,5,6])
arr2 = np.array([7,8,9,10])

print("Array 1 :",arr1)
print("Array 2 :",arr2)

print("Array 1 * Array 2 :",arr1*arr2)
print("Sum of Array 1 * Array 2 :",(arr1*arr2).sum())

Array 1 : [3 4 5 6]
Array 2 : [ 7  8  9 10]
Array 1 * Array 2 : [21 32 45 60]
Sum of Array 1 * Array 2 : 158


In [39]:
# Example 3
# Explanation : This will first subtraction arr1 and arr2 then sum of arr1 and arr2 subtraction.

arr1 = np.array([33,4,56,89])
arr2 = np.array([7,88,15,56])

print("Array 1 :",arr1)
print("Array 2 :",arr2)

print("Array 1 * Array 2 :",arr1-arr2)
print("Sum of Array 1 * Array 2 :",(arr1-arr2).sum())

Array 1 : [33  4 56 89]
Array 2 : [ 7 88 15 56]
Array 1 * Array 2 : [ 26 -84  41  33]
Sum of Array 1 * Array 2 : 16


# function np.reshape()

In [44]:
# Example 1 
# Explanation : This will reshape the 1D array [1, 2, 3, 4, 5, 6] into a 2D array with 2 rows, with the number of columns automatically calculated to be 3.

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = np.reshape(arr, (2, -1))
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
# Exampele 2
# Explanation: This will reshape the 1D array [1, 2, 3, 4, 5, 6, 7, 8] into a 2D array with 4 rows. The -1 in the shape tuple allows NumPy to automatically calculate the number of columns needed to maintain the total number of elements.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

reshaped_arr = np.reshape(arr, (4, -1))
reshaped_arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [42]:
# Exampele 3 
# Explanation: This will reshape the 2D array [[1, 2, 3], [4, 5, 6]] into a 1D array [1, 2, 3, 4, 5, 6].

arr = np.array([[1, 2, 3], [4, 5, 6]])

arr = np.reshape(arr, 6)
arr

array([1, 2, 3, 4, 5, 6])

# function 4 np.zeros()

In [52]:
# Example 1 
# Explanation: This will create a 2D array with 3 rows and 2 columns filled with zeros, stored in Fortran (column-major) order instead of the default C (row-major) order.

arr = np.zeros((3, 2), order='F')
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [51]:
# Example 2 
#Explanation: This will create a 1D array filled with integer zeros instead of the default floating-point zeros.

arr = np.zeros(5, dtype=int)
print(arr)

[0 0 0 0 0]


In [46]:
# Example 3 
# Explanation: This will create a 3D array with dimensions 2x3x4, all filled with zeros. It has 2 matrices, each with 3 rows and 4 columns, resulting in a shape of (2, 3, 4).


arr = np.zeros((2, 3, 4))
print(arr)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


# function 5 np.std()

In [53]:
# Example 1
# Explanation: This will calculate the standard deviation of the 1D array [1, 2, 3, 4, 5]. The standard deviation is a measure of the amount of variation or dispersion of a set of values. In this example, it computes the standard deviation of the elements in the array.

arr = np.array([1, 2, 3, 4, 5])

std = np.std(arr)

print(std)

1.4142135623730951


In [54]:
# Example 2 
# Explanation: This will calculate the standard deviation along the columns (axis=0) of the 2D array [[1, 2, 3], [4, 5, 6]]. It computes the standard deviation for each column separately and returns an array containing the standard deviation values for each column.

arr = np.array([[1, 2, 3], [4, 5, 6]])

std = np.std(arr, axis=0)

print(std)

[1.5 1.5 1.5]


In [55]:
# Exampale 3 
# Explanation: This will compute the sample standard deviation along the rows (axis=1) of the 2D array [[1, 2], [3, 4], [5, 6]] with degrees of freedom (ddof) set to 1. It computes the standard deviation for each row separately, considering each row as a sample.

arr = np.array([[1, 2], [3, 4], [5, 6]])

std = np.std(arr, axis=1, ddof=1)
print(std)


[0.70710678 0.70710678 0.70710678]
